### ISSUE TITLE
Mailbox/query parentId => null crashes

### ISSUE THREAD

**Issue by wolfsage** [cyrusimap/cyrus-imapd#2263]
The Mailbox/query spec says:

https://github.com/jmapio/jmap/blob/master/spec/mail/mailbox.mdown#mailboxquery

````
Mailbox/query

Standard /query method.

A FilterCondition object has the following properties, any of which may be omitted:

    parentId: String|null The Mailbox parentId property must match the given value exactly.
````

This is slightly ambiguous to me. Does this mean if I give `parentId => null` find all mailboxes with no `parentId`? Or ignore `parentId` as a filter entirely? (since `null` is the default value....).

In any case, if I hand in a `parentId` of `null`, we get a cyrus crash:

````
(gdb) bt
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
#1  0x00007f0ac235ecb2 in xstrdup (str=0x0) at lib/xmalloc.c:88
#2  0x00000000004b472b in mboxsearch_build_filter (query=0x16d49d0, 
    jfilter=0x170f990) at imap/jmap_mail.c:1096
#3  0x00000000004b4dab in jmapmbox_search (req=0x7fffcb5809a0, 
[...]
(gdb) list
1091	        json_t *val;
1092	        filter->op = SEOP_UNKNOWN;
1093	        if ((val = json_object_get(jfilter, "parentId"))) {
1094	            mboxsearch_field_t *field = xzmalloc(sizeof(mboxsearch_field_t));
1095	            field->name = xstrdup("parentId");
1096	            field->val.s = xstrdup(json_string_value(val));
1097	            ptrarray_append(&filter->args, field);
1098	        }
1099	        if ((val = json_object_get(jfilter, "hasRole"))) {
1100	            mboxsearch_field_t *field = xzmalloc(sizeof(mboxsearch_field_t));
````

**Comment by rsto** [comment]
Fixed with https://github.com/cyrusimap/cyrus-imapd/commit/c818b8d86cefb13b186b564feb649d113740b181

**Comment by wolfsage** [comment]
This still crashes, but elsewhere now.

````
#2  0x00000000004b529f in mboxsearch_build_filter (query=0x1660a50, 
    jfilter=0x169bf20) at imap/jmap_mail.c:1400
1400	            field->val.s = xstrdup(json_string_value(val));
(gdb) list
1395	        json_t *val;
1396	        filter->op = SEOP_UNKNOWN;
1397	        if ((val = json_object_get(jfilter, "parentId"))) {
1398	            mboxsearch_field_t *field = xzmalloc(sizeof(mboxsearch_field_t));
1399	            field->name = xstrdup("parentId");
1400	            field->val.s = xstrdup(json_string_value(val));
1401	            ptrarray_append(&filter->args, field);
1402	        }
1403	        if ((val = json_object_get(jfilter, "hasRole"))) {
````

json_object_get is returning a `json_is_null(val)` probably?

**Comment by rsto** [comment]
> json_object_get is returning a json_is_null(val) probably?

Nah, I was just closing the wrong issue. Expect a fix in the next minutes.

**Comment by wolfsage** [comment]
Ah, there is no ambiguity. "String|null" is listing possible types, not a default value of 'null'. That would be in a `(default: ...)` comment.

All set, thanks!
