### ISSUE TITLE
uninitialized value in IMAP.pm line 86 in rename without partition option

### ISSUE THREAD

**Issue by falon** [cyrusimap/cyrus-imapd#2712]
Hello,
  with Cyrus 3.0.8 if you try this:

```
#!/usr/bin/perl -w

$auth = {
                -mechanism => 'PLAIN',
                -service => 'imap',
                -authz => 'user@example.com',
                -user => 'user@example.com',
                -minssf => 0,
                -maxssf => 10000,
                -password => 'password',
};
$Server = 'localhost';

use Cyrus::IMAP::Admin;

$cyrus = Cyrus::IMAP::Admin->new($Server);
$cyrus->authenticate(%$auth);
$cyrus->rename('INBOX/test2', 'INBOX/test1');
```
let suppose it exists "INBOX/test2", the RENAME succeeds, but it leaves this warning:

`Use of uninitialized value in concatenation (.) or string at /usr/lib64/perl5/vendor_perl/Cyrus/IMAP.pm line 86.`
`Use of uninitialized value in concatenation (.) or string at /usr/lib64/perl5/vendor_perl/Cyrus/IMAP.pm line 86.`

**Comment by elliefm** [comment]
I think this also affects master. Looks like the issue is coming from here:

https://github.com/cyrusimap/cyrus-imapd/blob/e16ba8b42b2ddd0eeed063acfea303915246d57c/perl/imap/IMAP/Admin.pm#L639-L640

Note that `$self->send(...)` is a printf-like function, with a format string and a bunch of arguments.  It looks like the partition argument (`$ptn`) is being conditionalised out if it's not required, but the '%a' is still in the format string.  Thus we end up down in line 86 of IMAP.pm trying to concatenate an empty argument, and the warning results.

There is some weirdness here where the partition argument is conditionalised in once, and then included unconditionally right after, which I don't quite understand the rationale for (which is why I'm documenting my findings and not just banging out a fix...)

I think the fix will be two split this into two calls to `$self->send()`: one if there's a partition argument, the other if there's not, with each having the correct format string and arguments (no inline conditions).

**Comment by elliefm** [comment]
Okay I understand it now, I think this code was written a million years ago before everyone turned on warnings all the time.  Fix incoming shortly!

**Comment by elliefm** [comment]
This patch should fix it, can you try it out and let us know?  Thanks :)

https://github.com/elliefm/cyrus-imapd/commit/e0468cc97e14b8a7a5fc3c4893f03cffd1963a9f

**Comment by falon** [comment]
Hello Ellie, thank you again
I tried this, Perl claims that
`Parentheses missing around "my" list at Cyrus/IMAP/Admin.pm line 637`.

Maybe you missed parentheses. It is sufficient to change
`  my $rc, $msg;` into:
`  my ($rc, $msg);`
...and it works.

Thank you very much
Marco

**Comment by elliefm** [comment]
Thanks for testing that out! I'll get the parens fixed and merge it into mainline so that it's included in future releases.

The warning itself wasn't actually a problem, just perl being more helpful than it was when the old code was written, so you're fine to run it with or without the patch in the meantime (just ignore this warning)
